#!/usr/bin/env python3
"""
CITL Database LLMOps Builder
Wizard that exports a complete, runnable custom AI application as a
portfolio artifact: Python app + Modelfile + README + launcher scripts.
"""
from __future__ import annotations
import json, os, shutil, sys, textwrap, threading, zipfile
from datetime import date
from pathlib import Path
from typing import List, Optional

try:
    import tkinter as tk
    from tkinter import filedialog, messagebox, scrolledtext, ttk
except ImportError:
    sys.exit("tkinter required")

_HERE = Path(__file__).parent
if getattr(sys, "frozen", False):
    REPO = Path(sys.executable).parent.parent.parent
else:
    REPO = _HERE.parent
EXPORTS_DIR = REPO / "documents" / "llmops_exports"

C = {
    "bg": "#0D1B2A", "panel": "#112236", "panel_alt": "#162B40",
    "notebk": "#0C1A2C", "card_sel": "#1E4060",
    "text": "#D4E4F5", "muted": "#7A9BBE", "faint": "#3E5A78",
    "accent": "#3A8FD4", "gold": "#E89820",
    "btn": "#1A3550", "btn_hi": "#235272", "btn_acc": "#1A4A7A",
    "line": "#1D3050",
}
_F = "Segoe UI" if sys.platform == "win32" else "Ubuntu"
APP_NAME = "DATABASE LLMOps Builder"
APP_VERSION = "v1.0"

#  Generated app template 
_APP_TEMPLATE = '''\
#!/usr/bin/env python3
"""
{app_name}
{app_purpose}
Generated by CITL DATABASE LLMOps Builder on {build_date}.
"""
import json, sys, threading
from pathlib import Path
try:
    import tkinter as tk
    from tkinter import scrolledtext
except ImportError:
    sys.exit("tkinter required")

APP_NAME    = "{app_name}"
OLLAMA_HOST = "http://localhost:11434"
MODEL       = "{model}"
SYSTEM_PROMPT = """{system_prompt}"""
CORPUS_DIR  = Path(__file__).parent / "corpus"

def _chat(prompt: str) -> str:
    import urllib.request, urllib.error
    payload = json.dumps({{"model": MODEL, "prompt": prompt,
                           "system": SYSTEM_PROMPT, "stream": False}}).encode()
    try:
        req = urllib.request.Request(OLLAMA_HOST + "/api/generate",
                                     data=payload, method="POST")
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read())["response"].strip()
    except Exception as exc:
        return f"[Error: {{exc}}]"

class App:
    def __init__(self, root):
        self.root = root
        root.title(APP_NAME)
        root.configure(bg="#0D1B2A")
        root.minsize(780, 520)
        tk.Label(root, text=APP_NAME, font=("Segoe UI", 14, "bold"),
                 bg="#0D1B2A", fg="#E89820").pack(anchor="w", padx=14, pady=(10,2))
        self.log = scrolledtext.ScrolledText(root, wrap="word", height=20,
            bg="#0C1A2C", fg="#D4E4F5", insertbackground="#D4E4F5",
            relief="flat", font=("Consolas", 10))
        self.log.pack(fill="both", expand=True, padx=10, pady=4)
        row = tk.Frame(root, bg="#0D1B2A"); row.pack(fill="x", padx=10, pady=(0,10))
        self.entry = tk.Entry(row, bg="#112236", fg="#D4E4F5",
                              insertbackground="#D4E4F5", relief="flat", font=("Segoe UI",11))
        self.entry.pack(side="left", fill="x", expand=True, padx=(0,8))
        self.entry.bind("<Return>", self._send)
        tk.Button(row, text="Send", bg="#1A4A7A", fg="#D4E4F5",
                  relief="flat", padx=12, command=self._send).pack(side="left")
        self._append(f"{{APP_NAME}} ready. Type a question and press Enter.\\n")

    def _append(self, text):
        self.log.configure(state="normal")
        self.log.insert("end", text)
        self.log.see("end")
        self.log.configure(state="disabled")

    def _send(self, _e=None):
        prompt = self.entry.get().strip()
        if not prompt: return
        self.entry.delete(0, "end")
        self._append(f"You: {{prompt}}\\n")
        threading.Thread(target=self._respond, args=(prompt,), daemon=True).start()

    def _respond(self, prompt):
        reply = _chat(prompt)
        self.root.after(0, lambda: self._append(f"{{APP_NAME}}: {{reply}}\\n\\n"))

def main():
    root = tk.Tk()
    App(root)
    root.mainloop()

if __name__ == "__main__":
    main()
'''

_MODELFILE_TEMPLATE = """\
FROM {model}
SYSTEM \"\"\"{system_prompt}\"\"\"
PARAMETER temperature {temperature}
PARAMETER num_ctx {context_window}
"""

_README_TEMPLATE = """\
# {app_name}

**Purpose:** {app_purpose}

**Built with:** CITL DATABASE LLMOps Builder  |  **Date:** {build_date}

## Running the App

```
python {app_file}
```

Requires: Python 3.10+, Ollama running with `{model}` model available.

## Creating the Ollama Model

```
ollama create {model_tag} -f Modelfile
```

Then update `MODEL = "{model_tag}"` in `{app_file}`.

## Portfolio Notes

This application demonstrates:
- Local LLM deployment and configuration
- Custom system prompt engineering
- Corpus-based knowledge specialization
- GUI application development in Python
"""


class DatabaseLLMOpsBuilder:
    def __init__(self, root: tk.Tk):
        self.root = root
        root.title(f"{APP_NAME}  {APP_VERSION}")
        root.configure(bg=C["bg"])
        root.minsize(900, 640)
        EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

        # State
        self.corpus_files: List[Path] = []
        self.app_name_var    = tk.StringVar(value="My AI Assistant")
        self.purpose_var     = tk.StringVar(value="Answers questions about our department's knowledge base")
        self.model_var       = tk.StringVar(value="llama3.2:3b")
        self.temperature_var = tk.StringVar(value="0.3")
        self.ctx_var         = tk.StringVar(value="4096")
        self.status_var      = tk.StringVar(value="Step 1 - Configure your application")

        self._build_ui()

    #  UI 

    def _build_ui(self):
        # Header
        hdr = tk.Frame(self.root, bg=C["panel"])
        hdr.pack(fill="x")
        tk.Frame(hdr, bg=C["gold"], height=3).pack(fill="x")
        hi = tk.Frame(hdr, bg=C["panel"]); hi.pack(fill="x", padx=14, pady=8)
        tk.Label(hi, text=APP_NAME, font=(_F,15,"bold"), bg=C["panel"], fg=C["text"]).pack(side="left")
        tk.Label(hi, text=APP_VERSION, font=(_F,9,"bold"), bg=C["panel"], fg=C["gold"]).pack(side="left",padx=6)
        tk.Label(hi, text="Build, configure, and export a custom AI application",
                 font=(_F,9,"italic"), bg=C["panel"], fg=C["muted"]).pack(side="right")

        # Status bar
        tk.Label(self.root, textvariable=self.status_var, font=(_F,9),
                 bg=C["panel_alt"], fg=C["accent"], anchor="w", padx=12, pady=4).pack(fill="x")

        body = tk.Frame(self.root, bg=C["bg"]); body.pack(fill="both", expand=True, padx=10, pady=6)
        body.columnconfigure(0, weight=1); body.columnconfigure(1, weight=1)
        body.rowconfigure(0, weight=1)

        self._build_left(body)
        self._build_right(body)

    def _build_left(self, parent):
        left = tk.Frame(parent, bg=C["panel"]); left.grid(row=0,column=0,sticky="nsew",padx=(0,5))
        left.columnconfigure(1, weight=1)
        row = 0

        def _field(label, var, height=1):
            nonlocal row
            tk.Label(left, text=label, font=(_F,8), bg=C["panel"], fg=C["muted"],
                     anchor="w").grid(row=row, column=0, sticky="w", padx=(10,6), pady=3)
            if height == 1:
                tk.Entry(left, textvariable=var, font=(_F,10), bg=C["notebk"],
                         fg=C["text"], insertbackground=C["text"], relief="flat",
                         highlightthickness=0).grid(row=row, column=1, sticky="ew", padx=(0,10), pady=3)
            row += 1

        self._lbl(left, "STEP 1 - APP IDENTITY").grid(row=row,column=0,columnspan=2,
                                                        sticky="w",padx=10,pady=(10,4)); row+=1
        _field("App name:", self.app_name_var)
        _field("Purpose / description:", self.purpose_var)

        self._lbl(left, "STEP 2 - CORPUS DOCUMENTS").grid(row=row,column=0,columnspan=2,
                                                            sticky="w",padx=10,pady=(10,4)); row+=1
        self.corpus_lbl = tk.Label(left, text="No documents added yet.", font=(_F,8,"italic"),
                                   bg=C["panel"], fg=C["faint"], anchor="w", wraplength=300)
        self.corpus_lbl.grid(row=row,column=0,columnspan=2,sticky="ew",padx=10); row+=1
        btn_row = tk.Frame(left, bg=C["panel"]); btn_row.grid(row=row,column=0,columnspan=2,sticky="ew",padx=10,pady=(4,8)); row+=1
        self._btn(btn_row,"Add Documents",C["btn"],self._add_docs).pack(side="left",padx=(0,6))
        self._btn(btn_row,"Clear",C["btn"],self._clear_docs).pack(side="left")

        self._lbl(left, "STEP 3 - MODEL & PERSONA").grid(row=row,column=0,columnspan=2,
                                                           sticky="w",padx=10,pady=(10,4)); row+=1
        _field("Ollama model:", self.model_var)
        _field("Temperature (0-1):", self.temperature_var)
        _field("Context window:", self.ctx_var)

        self._lbl(left, "SYSTEM PROMPT").grid(row=row,column=0,columnspan=2,
                                               sticky="w",padx=10,pady=(10,4)); row+=1
        self.prompt_box = scrolledtext.ScrolledText(left, height=6, wrap="word",
            font=(_F,9), bg=C["notebk"], fg=C["text"], insertbackground=C["text"], relief="flat")
        self.prompt_box.grid(row=row,column=0,columnspan=2,sticky="ew",padx=10,pady=(0,8)); row+=1
        self.prompt_box.insert("1.0",
            "You are a helpful, professional AI assistant. "
            "Answer questions accurately and concisely based on the provided documents. "
            "If unsure, say so clearly.")

    def _build_right(self, parent):
        right = tk.Frame(parent, bg=C["panel"]); right.grid(row=0,column=1,sticky="nsew")
        right.rowconfigure(2,weight=1)
        right.columnconfigure(0,weight=1)

        self._lbl(right,"STEP 4 - PREVIEW & EXPORT").grid(row=0,column=0,sticky="w",padx=10,pady=(10,4))
        info_text = (
            "Export creates a self-contained portfolio package:\n"
            "  - app.py         - runnable Python AI application\n"
            "  - Modelfile      - Ollama model configuration\n"
            "  - README.md      - setup + portfolio notes\n"
            "  - run_windows.cmd / run_ubuntu.sh - launchers\n"
            "  - corpus/        - your uploaded documents\n\n"
            "Open the ZIP to see your project.\n"
            "Run the app to demo it to employers."
        )
        tk.Label(right, text=info_text, font=(_F,9), bg=C["panel"], fg=C["muted"],
                 justify="left", anchor="nw", padx=10).grid(row=1,column=0,sticky="ew")

        self.log = scrolledtext.ScrolledText(right, wrap="word", height=12, state="disabled",
            font=("Consolas",9), bg=C["notebk"], fg=C["text"], relief="flat")
        self.log.grid(row=2,column=0,sticky="nsew",padx=10,pady=(6,4))

        btn_frame = tk.Frame(right, bg=C["panel"]); btn_frame.grid(row=3,column=0,sticky="ew",padx=10,pady=(0,10))
        btn_frame.columnconfigure(0,weight=1); btn_frame.columnconfigure(1,weight=1)
        self._btn(btn_frame,"Export App Package ",C["btn_acc"],self._export).grid(row=0,column=0,sticky="ew",padx=(0,4))
        self._btn(btn_frame,"Open Exports Folder",C["btn"],self._open_exports).grid(row=0,column=1,sticky="ew",padx=(4,0))

    #  Helpers 

    def _lbl(self, parent, text):
        return tk.Label(parent, text=text, font=(_F,8,"bold"), bg=C["panel"], fg=C["accent"])

    def _btn(self, parent, text, bg, cmd):
        return tk.Button(parent, text=text, font=(_F,9), bg=bg, fg=C["text"],
                         activebackground=C["btn_hi"], relief="flat", bd=0,
                         padx=8, pady=5, cursor="hand2", command=cmd)

    def _log(self, msg):
        self.log.configure(state="normal")
        self.log.insert("end", msg)
        self.log.see("end")
        self.log.configure(state="disabled")

    def _add_docs(self):
        paths = filedialog.askopenfilenames(
            title="Add corpus documents",
            filetypes=[("Text / PDF / Word", "*.txt *.pdf *.docx *.md *.csv"),("All","*.*")])
        if not paths:
            return
        seen = {str(p) for p in self.corpus_files}
        for p in paths:
            if p not in seen:
                self.corpus_files.append(Path(p))
                seen.add(p)
        self.corpus_lbl.config(text=f"{len(self.corpus_files)} document(s) added.")

    def _clear_docs(self):
        self.corpus_files.clear()
        self.corpus_lbl.config(text="No documents added yet.")

    def _open_exports(self):
        EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
        if sys.platform == "win32":
            os.startfile(str(EXPORTS_DIR))
        else:
            import subprocess; subprocess.Popen(["xdg-open", str(EXPORTS_DIR)])

    #  Export 

    def _export(self):
        app_name = self.app_name_var.get().strip() or "My AI Assistant"
        purpose  = self.purpose_var.get().strip() or "AI assistant"
        model    = self.model_var.get().strip() or "llama3.2:3b"
        temp     = self.temperature_var.get().strip() or "0.3"
        ctx      = self.ctx_var.get().strip() or "4096"
        sys_prompt = self.prompt_box.get("1.0","end-1c").strip()
        build_date = str(date.today())

        slug = "".join(c if c.isalnum() or c in "_-" else "_" for c in app_name).strip("_") or "my_ai_app"
        model_tag = slug.lower()
        app_file  = f"{slug}.py"

        self.status_var.set("Exporting...")
        self._log(f"\n[EXPORT] Building package for: {app_name}\n")

        def worker():
            try:
                out_zip = EXPORTS_DIR / f"{slug}_{build_date.replace('-','')}.zip"
                with zipfile.ZipFile(out_zip, "w", compression=zipfile.ZIP_DEFLATED) as zf:
                    # app.py
                    app_src = _APP_TEMPLATE.format(
                        app_name=app_name, app_purpose=purpose,
                        build_date=build_date, model=model,
                        system_prompt=sys_prompt.replace('"','\\"'))
                    zf.writestr(app_file, app_src)

                    # Modelfile
                    zf.writestr("Modelfile", _MODELFILE_TEMPLATE.format(
                        model=model, system_prompt=sys_prompt.replace('"','\\"'),
                        temperature=temp, context_window=ctx))

                    # README
                    zf.writestr("README.md", _README_TEMPLATE.format(
                        app_name=app_name, app_purpose=purpose,
                        build_date=build_date, model=model,
                        model_tag=model_tag, app_file=app_file))

                    # Windows launcher
                    zf.writestr("run_windows.cmd",
                        f"@echo off\npython {app_file} %*\npause\n")

                    # Ubuntu launcher
                    zf.writestr("run_ubuntu.sh",
                        f"#!/usr/bin/env bash\nexec python3 \"$(dirname \"$0\")/{app_file}\" \"$@\"\n")

                    # corpus folder
                    for doc in self.corpus_files:
                        if doc.is_file():
                            zf.write(doc, arcname=f"corpus/{doc.name}")
                            self.root.after(0, lambda n=doc.name: self._log(f"  + corpus/{n}\n"))

                    # config json
                    cfg = {"app_name":app_name,"purpose":purpose,"model":model,
                           "temperature":temp,"context_window":ctx,"build_date":build_date}
                    zf.writestr("config.json", json.dumps(cfg, indent=2))

                pkg_size = out_zip.stat().st_size
                self.root.after(0, lambda: (
                    self._log(f"[EXPORT] Done: {out_zip.name}  ({pkg_size//1024} KB)\n"),
                    self.status_var.set(f"Exported: {out_zip.name}"),
                    messagebox.showinfo(APP_NAME,
                        f"Package exported:\n{out_zip}\n\nUnzip it to demo your app to employers.\n"
                        "Run: python " + app_file)
                ))
            except Exception as exc:
                self.root.after(0, lambda: (
                    self._log(f"[EXPORT][ERROR] {exc}\n"),
                    self.status_var.set("Export failed - see log.")))

        threading.Thread(target=worker, daemon=True).start()


def main():
    root = tk.Tk()
    root.withdraw()
    try:
        root.tk.call("tk", "scaling", 1.25)
    except Exception:
        pass
    root.deiconify()
    DatabaseLLMOpsBuilder(root)
    root.mainloop()


if __name__ == "__main__":
    main()
